export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {/* <header style={{backgroundColor:"green" ,padding:'1rem'}}>
          <p className=" bg-green-500"> Header</p>
        </header> */}
        {children}
        {/* <footer style={{backgroundColor:"green" ,padding:'1rem'}}>
          <p>Footer</p>
        </footer> */}
        </body>
    </html>
  )
}
