"use client";

import { Inter } from "next/font/google";
import Link from "next/link";
import { usePathname } from "next/navigation";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // function getRandomInt(count:number){
//     return Math.floor(Math.random()*count);
// }
// const random=getRandomInt(3)
// if(random===1){
//   throw new Error("Error here")
// }
  
  const navlinks :{name:string,href:string}[]=[
    {name:"Login",href:"/login"},
    {name:"Register",href:"/register"},
    {name:"Forgot Password",href:"/forgot-password"},
    
  ]
  const pathname=usePathname()
  return (
    <html lang="en">
      
      <body className={inter.className}>
      <div className="  w-screen p-4 bg-orange-700
      ">
        {
          navlinks.map((navlink)=>{
            const isActive=pathname.startsWith(navlink.href);
           return(
            <Link href={navlink.href} key={navlink.name} className={` p-4 ${isActive  ? "text-green-500" :""}`}   >{navlink.name}</Link>
           )
          })
        }
      </div>
     
        {children}
        
        
        </body>
    </html>
  );
}
